[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "trading"
version = "0.1.0"
description = "Crypto Trading Platform"
requires-python = ">=3.9"

[tool.pytest.ini_options]
pythonpath = [
    "."
]